os:
  - linux
dist: xenial
language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
install:
  - pip install nose requests coverage
  - nohup python -m server --port 8443 &
  - sleep 2
script:
  - nosetests --verbosity=2 --with-coverage --cover-erase --cover-xml --cover-package=server
after_success:
  - bash <(curl -s https://codecov.io/bash)
